import React from 'react';

const SampleMusic = () => {
  return (
    <div className="p-6">
      <h2 className="text-2xl font-bold mb-4">Sample Music</h2>
      <p>Explore some sample music generated by our AI.</p>
    </div>
  );
};

export default SampleMusic;
